//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Core.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Core.Resource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra vui lòng liên hệ MISA để được trợ giúp.
        /// </summary>
        public static string Error_Exception {
            get {
                return ResourceManager.GetString("Error_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài sản này đã có rồi. Vui lòng nhập mã tài sản khác.
        /// </summary>
        public static string ErrorValidare_CheckDuplicatAssetCode {
            get {
                return ResourceManager.GetString("ErrorValidare_CheckDuplicatAssetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đàu vào không hợp lệ.
        /// </summary>
        public static string ErrorValidate {
            get {
                return ResourceManager.GetString("ErrorValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài sản không được phép để trống.
        /// </summary>
        public static string ErrorValidate_AssetName_NotEmpty {
            get {
                return ResourceManager.GetString("ErrorValidate_AssetName_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguyên giá không được phép để trống.
        /// </summary>
        public static string ErrorValidate_Cost_NotEmpty {
            get {
                return ResourceManager.GetString("ErrorValidate_Cost_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phòng ban không được phép để trống.
        /// </summary>
        public static string ErrorValidate_DepartmentCode_NotEmpty {
            get {
                return ResourceManager.GetString("ErrorValidate_DepartmentCode_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỷ lệ hao mòn không được phép để trống.
        /// </summary>
        public static string ErrorValidate_DepreciationRate_NotEmpty {
            get {
                return ResourceManager.GetString("ErrorValidate_DepreciationRate_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã loại tài sản không được phép để trống.
        /// </summary>
        public static string ErrorValidate_FixedAssetCategoryCode_NotEmpty {
            get {
                return ResourceManager.GetString("ErrorValidate_FixedAssetCategoryCode_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số năm sử dụng không được phép để trống.
        /// </summary>
        public static string ErrorValidate_LifeTime_NotEmpty {
            get {
                return ResourceManager.GetString("ErrorValidate_LifeTime_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin {0} không được vượt quá {1} kí tự.
        /// </summary>
        public static string ErrorValidate_PropertyMaxLength {
            get {
                return ResourceManager.GetString("ErrorValidate_PropertyMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin {0} không được phép để trống.
        /// </summary>
        public static string ErrorValidate_PropertyNotNull {
            get {
                return ResourceManager.GetString("ErrorValidate_PropertyNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày mua không được phép để trống.
        /// </summary>
        public static string ErrorValidate_PurchaseDate_NotEmpty {
            get {
                return ResourceManager.GetString("ErrorValidate_PurchaseDate_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng không được phép để trống.
        /// </summary>
        public static string ErrorValidate_Quantity_NotEmpty {
            get {
                return ResourceManager.GetString("ErrorValidate_Quantity_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài sản không được phép để trống.
        /// </summary>
        public static string ErrorValidte_AssetCode_NotEmpty {
            get {
                return ResourceManager.GetString("ErrorValidte_AssetCode_NotEmpty", resourceCulture);
            }
        }
    }
}
